export const SCREEN_NAME = Object.freeze({
  WEB_VIEW: 'WEB_VIEW',
  MAIN_TABS: 'MAIN_TABS',
  COMPONENT_LIST: 'COMPONENT_LIST',
  FORM: 'FORM',
  SETTINGS: 'SETTINGS',
  SIGN_IN: 'SIGN_IN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SIGN_IN_PHONE_NO: 'SIGN_IN_PHONE_NO',
});

export const EVENT_NAME = Object.freeze({
  SIGN_IN_FACEBOOK: 'SIGN_IN_FACEBOOK',
  SIGN_IN_GOOGLE: 'SIGN_IN_GOOGLE',
  SIGN_IN_APPLE: 'SIGN_IN_APPLE',
  SIGN_IN_PHONE_NO: 'SIGN_IN_PHONE_NO',
  SIGN_IN_EMAIL: 'SIGN_IN_FACEBOOK',
  RECOVER_PASSWORD: 'RECOVER_PASSWORD',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_PRIMARY_COLOR: 'CHANGE_PRIMARY_COLOR',
});
