export const SCREEN_NAME = Object.freeze({
  WEB_VIEW: 'WEB_VIEW',
  MAIN_TABS: 'MAIN_TABS',
  COMPONENT_LIST: 'COMPONENT_LIST',
  SETTINGS: 'SETTINGS',
  SIGN_IN: 'SIGN_IN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  SIGN_IN_PHONE_NO: 'SIGN_IN_PHONE_NO',
});
